apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order.api
  template:
    metadata:
      labels:
        app: order.api
    spec:
      containers:
        - name: order-api # should not have '.' in the name
          image: hasanslayer/order-api:latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__OrderingConnectionString
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: order_connectionString
            - name: EventBusSettings__HostAddress
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: eventBus_settings
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
spec:
  selector:
    app: order.api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31004
  type: NodePort
