apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb # should not have '.' in the name
          image: mcr.microsoft.com/mssql/server:2017-latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: Admin1234567
            - name: ACCEPT_EULA
              value: "Y"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: orderdb
spec:
  selector:
    app: orderdb
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: ClusterIP
