apiVersion: v1
kind: ConfigMap
metadata: 
  name: order-configmap
data:
  eventBus_settings: amqp://guest:guest@rabbitmq:5672
  order_connectionString: Server=orderdb;Database=OrderDb;User Id=sa;Password=Admin1234567;Encrypt=False;TrustServerCertificate=True