apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch.api
  template:
    metadata:
      labels:
        app: elasticsearch.api
    spec:
      containers:
        - name: elasticsearch # should not have '.' in the name
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2 # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          env:
            - name: xpack.monitoring.enabled
              value: "true"
            - name: xpack.watcher.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.type
              value: "single-node"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch.api
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 31008
  type: NodePort
