apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetrunbasics-deployment
  labels:
    app: aspnetrunbasics.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetrunbasics
  template:
    metadata:
      labels:
        app: aspnetrunbasics
    spec:
      containers:
        - name: aspnetrunbasics # should not have '.' in the name
          image: hasanslayer/aspnetrunbasics:latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ApiSettings__GatewayAddress
              valueFrom:
                configMapKeyRef:
                  name: aspnetrunbasics-configmap
                  key: GatewayAddress
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetrunbasics-service
spec:
  selector:
    app: aspnetrunbasics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31007
  type: NodePort
