apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=           # "admin" base64 encoded
  mongo-root-password: YWRtaW4xMjM0NTY3  # "admin1234567" base64 encoded
