apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=           # "admin"
  mongo-root-password: YWRtaW4xMjM0NTY3  # "admin1234567"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
  labels:
    app: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
      - name: catalogdb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: catalogdb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalogdb-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: catalogdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalogdb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog.api
  template:
    metadata:
      labels:
        app: catalog.api
    spec:
      containers:
      - name: catalog-api # should not have '.' in the name
        image: hasanslayer/catalog-api:latest  # <-- Replace with your image name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DatabaseSettings__ConnectionString
          value: mongodb://admin:admin1234567@catalogdb-service:27017/?authSource=admin
        - name: ElasticConfiguration__Uri
          value: http://elasticsearch-service:9200
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalog.api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
  type: NodePort
