apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb-deployment
  labels:
    app: basketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
        - name: basketdb # should not have '.' in the name
          image: redis:6.0-alpine # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basketdb-service
spec:
  selector:
    app: basketdb
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
