apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-api-deployment
  labels:
    app: discount.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount.api
  template:
    metadata:
      labels:
        app: discount.api
    spec:
      containers:
        - name: discount-api # should not have '.' in the name
          image: hasanslayer/discount-api:latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: connection_string
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  selector:
    app: discount.api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
  type: NodePort
