apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountdb-deployment
  labels:
    app: discountdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountdb
  template:
    metadata:
      labels:
        app: discountdb
    spec:
      containers:
        - name: discountdb
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-db
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: discountdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: discountdb-service
spec:
  selector:
    app: discountdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP