apiVersion: v1
kind: Secret
metadata:
  name: discountdb-secret
type: Opaque
data:
  postgres-username: YWRtaW4= # "admin"
  postgres-password: YWRtaW4xMjM0NTY3 # "admin1234567"
  postgres-db: RGlzY291bnREYg== # "DiscountDb"