apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
  labels:
    app: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: catalogdb # should not have '.' in the name
          image: mongo:latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalogdb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
