version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234567
      - POSTGRES_DB=DiscountDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Admin1234567"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
  

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234567
    restart: always
    ports:
      - "5050:8080"
    volumes:
      - pgadmin_data:/root/.pgadmin 
  

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:8080" 
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - basketdb 
      - rabbitmq
    ports:
      - "8001:8080"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234567;" 
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch

    depends_on:
      - discountdb 
    ports:
      - "8002:8080"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234567;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - discountdb 
    ports:
      - "8003:8080"
       
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Admin1234567;Encrypt=False;TrustServerCertificate=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - orderdb 
      - rabbitmq
    ports:
      - "8004:8080"


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - catalog.api 
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8010:8080"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api:8080"
      - "ApiSettings:BasketUrl=http://basket.api:8080"
      - "ApiSettings:OrderingUrl=http://ordering.api:8080"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:8080"


  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw:8080" # from ocelotapigw container name
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" # - http://container_name_of_elasticsearch:port_of_elasticsearch
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api

    ports:
      - "8006:8080"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"


  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
 # override appsetting HealthChecksUI array to make it work inside docker environemnt
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api:8080/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api:8080/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api:8080/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api:8080/hc
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator:8080/hc
      - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://aspnetrunbasics:8080/hc
    ports:
      - "8007:8080"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

