apiVersion: v1
kind: ConfigMap
metadata:
  name: webstatus-configmap
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "8080"
  HealthChecksUI__HealthChecks__0__Name: Catalog Health Check
  HealthChecksUI__HealthChecks__0__Uri: http://catalogapi-service:8080/hc
  HealthChecksUI__HealthChecks__1__Name: Basket Health Check
  HealthChecksUI__HealthChecks__1__Uri: http://basketapi-service:8080/hc
  HealthChecksUI__HealthChecks__2__Name: Discount Health Check
  HealthChecksUI__HealthChecks__2__Uri: http://discountapi-service:8080/hc
  HealthChecksUI__HealthChecks__3__Name: Ordering Health Check
  HealthChecksUI__HealthChecks__3__Uri: http://orderapi-service:8080/hc
  HealthChecksUI__HealthChecks__4__Name: Shopping Aggregator Health Check
  HealthChecksUI__HealthChecks__4__Uri: http://shopping-aggregator-service:8080/hc
  HealthChecksUI__HealthChecks__5__Name: AspnetRunBasics WebMVC Health Check
  HealthChecksUI__HealthChecks__5__Uri: http://aspnetrunbasics-service:8080/hc
