apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstatus-deployment
  labels:
    app: webstatus.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webstatus
  template:
    metadata:
      labels:
        app: webstatus
    spec:
      containers:
        - name: webstatus # should not have '.' in the name
          image: hasanslayer/webstatus:latest # <-- Replace with your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: webstatus-configmap
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webstatus-service
spec:
  selector:
    app: webstatus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31010
  type: NodePort
