name: Build, Push to Docker Hub, and Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/Services/Catalog/Catalog.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/catalog-api:latest

    - name: Install Fly CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "${HOME}/.fly/bin" >> $GITHUB_PATH

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --image docker.io/${{ secrets.DOCKER_USERNAME }}/catalog-api:latest
